export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/Auth/login',
    REGISTER: '/Auth/register',
    REGISTER_COMPANY: '/Auth/register/companies',
    SEND_OTP: '/Auth/send-registration-otp',
    VERIFY_OTP: '/Auth/verify-registration-otp',
    LOGOUT: '/Auth/logout',
    USER_TYPE: '/Auth/user-type',
  },
  ADMIN: {
    GOVERNORATES: '/Admin/governorates',
    GOVERNORATE_DETAILS: (id: number) => `/Admin/governorates/${id}`,
    GOVERNORATE_CITIES: (govId: number) => `/Admin/cities/by-governorate/${govId}`,
    CITIES: '/Admin/cities',
    CITY_DETAILS: (id: number) => `/Admin/cities/${id}`,
    BANKS: '/Admin/banks',
    BANK_DETAILS: (id: number) => `/Admin/banks/${id}`,
    PARTNER_COMPANIES: '/Admin/partner-companies',
    PARTNER_DETAILS: (id: number) => `/Admin/partner-companies/${id}`,
    CUSTOMERS: '/Admin/Customers',
    CUSTOMER_DETAILS: (id: number) => `/Admin/Customers/${id}`,
    ACTIVATE_CUSTOMER: (id: number) => `/Admin/Customers/${id}/activate`,
    DEACTIVATE_CUSTOMER: (id: number) => `/Admin/Customers/${id}/deactivate`,
    COMPANIES: '/Admin/companies',
    COMPANY_DETAILS: (id: number) => `/Admin/companies/${id}`,
    ACTIVATE_COMPANY: (id: number) => `/Admin/companies/${id}/activate`,
    DEACTIVATE_COMPANY: (id: number) => `/Admin/companies/${id}/deactivate`,
    TOGGLE_COMPANY_ACTIVATION: (userId: number) => `/Admin/toggle-activation/${userId}`,
    PENDING_COMPANIES: '/Admin/registrations/companies/pending',
    PENDING_SUBSCRIPTIONS: '/Admin/subscriptions/pending',
    ACCEPT_SUBSCRIPTION: (id: number) => `/Admin/subscriptions/${id}/accept`,
    REJECT_SUBSCRIPTION: (id: number) => `/Admin/subscriptions/${id}/reject`,
    ADS: '/Admin/ads',
    AD_DETAILS: (id: number) => `/Admin/ads/${id}`,
    STATS: '/Admin/stats',
    DASHBOARD_STATS: '/Admin/dashboard-stats',
    COMPLAINTS: '/Admin/complaints',
    COMPLAINTS_COMPANY: '/Admin/complaints/company',
    COMPLAINTS_TECHNICAL: '/Admin/complaints/technical',
    RESPOND_COMPANY_COMPLAINT: (id: number) => `/Admin/complaints/${id}/respond/company`,
    RESPOND_TECHNICAL_COMPLAINT: (id: number) => `/Admin/complaints/${id}/respond/technical`,
  },
  COMPANY: {
    DASHBOARD_STATS: '/Company/stats',
    TRIPS: '/Company/trips',
    TRIP_DETAILS: (id: number) => `/Company/trips/${id}`,
    TRIP_ROUTES: (tripId: number) => `/Company/trips/${tripId}/routes`,
    TRIP_ROUTE_DETAILS: (id: number) => `/Company/trips/routes/${id}`,
    TRIP_BOOKINGS: (tripId: number) => `/Company/trips/${tripId}/bookings`,
    BUSES: '/Company/buses',
    BUS_DETAILS: (id: number) => `/Company/buses/${id}`,
    BUS_TOGGLE_MAINTENANCE: (id: number) => `/Company/buses/${id}/toggle-maintenance`,
    BANK_ACCOUNTS: '/Company/bank/accounts',
    BANK_ACCOUNT_DETAILS: (id: number) => `/Company/bank/accounts/${id}`,
    STATIONS: '/Company/stations',
    STATION_DETAILS: (stationId: number) => `/Company/stations/${stationId}`,
    TRIP_FARES: '/Company/trip/fares',
    TRIP_FARE_DETAILS: (id: number) => `/Company/trip/fares/${id}`,
    SUBSCRIPTION_RENEW: '/Company/subscriptions/renew',
    SUBSCRIPTION_PLANS: '/Company/subscriptions/plans',
    PENDING_BOOKINGS: '/Company/trip/bookings/pending',
    CONFIRM_BOOKING: (id: number) => `/Company/trip/bookings/${id}/confirm`,
    REJECT_BOOKING: (id: number) => `/Company/trip/bookings/${id}/reject`,
    CANCELLATIONS: '/Company/trip/bookings/cancellations',
    ACCEPT_CANCELLATION: (id: number) => `/Company/trip/bookings/${id}/cancellation/accept`,
    REJECT_CANCELLATION: (id: number) => `/Company/trip/bookings/${id}/cancellation/reject`,
    SCAN_TICKET: (qrCode: string) => `/Company/trip/bookings/scan?qrCode=${encodeURIComponent(qrCode)}`,
  },
  NOTIFICATION: {
    MY_NOTIFICATIONS: '/Notification/my-notifications',
    MARK_READ: (id: number) => `/Notification/${id}/read`,
  }
};
